@startuml
Idle: state=Idle
Idle: probing
Idle: error?
Idle: ...........................................
Idle: probe()

Ready: state=Ready
Ready: available
Ready: vendor?

[*] --> Idle
Idle -> Ready :probe
@enduml
