@startuml
Idle: state=Idle
Idle: connecting
Idle: error?

Connected: state=Connected
Connected: loadingData
Connected: chainId
Connected: notSupported
Connected: error?

Ready: state=Ready
Ready: contracts
Ready: chainId
Ready: addresses
Ready: error?


[*] --> Idle
Idle -> Connected
Connected -> Ready
@enduml
