@startuml
Idle: state=Idle
Idle: connecting
Idle: options
Idle: selected?
Idle: error?
Idle: ................................
Idle: acknowledgeError()
Idle: connect(<type>)

Locked: state=Locked
Locked: unlocking
Locked: options
Locked: selected
Locked: error?
Locked: ................................
Locked: acknowledgeError()
Locked: unlock()
Locked: disconnect()

Ready: state=Ready
Ready: options
Ready: selected
Ready: address
Ready: error?
Ready: pendingUserConfirmation?
Ready: ................................
Ready: acknowledgeError()
Ready: disconnect()


[*] --> Idle
Idle -> Locked :connect
Ready -[dashed]> Locked
Idle -> Ready :connect
Locked --> Ready :unlock
Ready -> Idle :disconnect
Locked -> Idle :disconnect
@enduml
