@startuml
Idle: state=Idle
Idle: loading
Idle: options
Idle: selected?
Idle: error?
Idle: ................................
Idle: acknowledgeError()
Idle: connect(<type>)
Locked: state=Locked
Locked: unlocking
Locked: options
Locked: selected
Locked: error?
Locked: ................................
Locked: acknowledgeError()
Locked: unlock()
Locked: logout()
Ready: state=Ready
Ready: options
Ready: selected
Ready: address
Ready: error?
Ready: pendingUserConfirmation?
Ready: ................................
Ready: acknowledgeError()
Ready: logout()
Ready: .contracts...
Ready: .provider... // TODO


[*] --> Idle
Idle -> Locked
Idle -> Ready
Locked -> Ready
Ready -> Locked
@enduml
